---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: django-app
commonLabels:
  app: django-app
bases:
  - ../../base
images:
  - name: soydiegomen/django_hello_app
    newName: soydiegomen/django_hello_app
    newTag: v1.0.2